mas-cli/mas

README.md
Removing a couple duped words in the `mas search` example.
=> Correct `mas search` example

mas-cli.xcodeproj/project.pbxproj
By default, Xcode 8 requires the project to be written in Swift 3. However, Xcode 8 is still in beta, so it might be a better idea to enable the «Use Legacy Swift Language Version» option to make it working in Xcode 8 rather than converting the source to Swift 3.
=> Xcode 8 compatibility

Seedfile
Downloading a specific release of Curry prevents unexpected breaks due to changes being made in the master branch of that project.
=> Fix thoughtbot/Curry version in Seedfile

mas-cli/Commands/List.swift, mas-cli/Commands/Outdated.swift, mas-cli/PrivateHeaders/CommerceKit/CKSoftwareMap.h
=> Display app versions

.bundle/config, script/build
Install gems to local .rubygems folder.
Hoping this fixes the [build error](https://travis-ci.org/mas-cli/mas/jobs/333802088#L781) from running `bundle install`.
=> 💎 Configure bundler

mas-cli.xcodeproj/project.pbxproj, mas-cli/AppStore/CKSoftwareMap+AppLookup.swift, mas-cli/Commands/Upgrade.swift
This commit adds a step to the upgrade command which checks each
input token against the list of installed apps and converts any
matched productName to a productId.
=> support app name(s) for upgrade command.

CHANGELOG.md, mas-cli/Commands/Search.swift
not much more to say!
old:
```
$ mas search quip
1003160018 Quip
1002623276 Quiplash
```
new hotness:
```
$ ./mas search quip
1003160018 Quip 5.2.18
1002623276 Quiplash 1.0.0
```
=> add version to search

.travis.yml, App/main.swift, CHANGELOG.md
Testing that Danger works when PR is opened from a fork.
Danger token was flagged as "secure" which [excluded it from fork PRs](https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions).
=> 👷🏻‍♀️⚠️ Re-enable danger on Travis

App/Commands/Search.swift, CHANGELOG.md
Add '--price' parameter to search command to list prices.
Clearer formatting in search command, too.
=> Issue #62 Adding price in search

Homebrew/mas.rb, contrib/completion/mas-completion.bash
Just a simple completion script to make use of mas easier.
=> Adding simple bash completion

.gitignore, CHANGELOG.md, Homebrew/mas--1.4.2.high_sierra.bottle.json, Homebrew/mas-tap.rb, Homebrew/mas.rb, README.md
Changes to the `install` function to fetch bundler and run the `pod install` command. Thank goodness for the [`swiftgen`](https://github.com/Homebrew/homebrew-core/blob/d3e8bb0dfdf5c3ed4a4a72645805290169b88c66/Formula/swiftgen.rb#L21-L26) formula because I don't know if I could have figured that out.
New formula updated in Homebrew/homebrew-core#31058
=> 🍺 Homebrew formula update for 1.4.2

CHANGELOG.md, MasKit/Commands/Open.swift, MasKitTests/Commands/OpenCommandSpec.swift, script/uninstall
Building on #196, I thought it would be handy to use `mas open` without any further arguments to simply open the AppStore.app.
~~However, I'm not sure it's possible to make the appId argument optional through Commandant.~~
```
$ mas open
Missing argument for the app id
```
Ended up using a marker value of "appstore" so the following two commands are equivalent:
```
$ mas open
$ mas open appstore
```
=> 👐🏻 Open AppStore.app

.github/ISSUE_TEMPLATE/bug_report.md, .hound.yml, .shellcheck.yml, Brewfile, CHANGELOG.md, Dangerfile, Gemfile.lock, MasKit/Formatters/SearchResultFormatter.swift, MasKitTests/Formatters/SearchResultFormatterSpec.swift, mas-cli.xcodeproj/project.pbxproj, mas.xcworkspace/contents.xcworkspacedata, script/build, script/lint, script/package, script/swiftlint_runscript, script/uninstall, script/update_headers
Restored newline between each search result in `search` output. Added `SearchResultsFormatterSpec` to validate and help prevent regressions.
Also added "Actual behavior" section to issue template and removed duplicate source references from workspace.
Fixes #203
=> 🐛 Restore search table output

Homebrew/mas-tap.rb, Homebrew/mas.rb, contrib/completion/mas.fish
This changeset adds completions for [fish shell.](https://fishshell.com)
[![asciicast](https://asciinema.org/a/224252.svg)](https://asciinema.org/a/224252)
Once this PR is approved, I would be happy to submit another one to also support fish in Homebrew formula.
=> 📺 Add completions for fish shell

Homebrew/mas-tap.rb, Homebrew/mas.rb, script/brew_formula_bump, script/brew_formula_update
New script wrapping the `brew bump-formula-pr` command. Hasn't been used to actually perform a release, but it looks like it can do most of the work.
1. Compares `Homebrew/mas.rb` to `$BREW_CORE_PATH/mas.rb`
- differences will need to be manually applied
1. Run `bump-formula-pr` in validation mode
1. If there were differences between the local and core formulas:
- bump the version in `--write` mode, allowing the user to manually apply the changes before opening a PR on homebrew-core
- otherwise, open a PR
Note that this script hasn't been fully tested with a full formula update.
=> 🧪📜 Update Homebrew formula, add brew_formula_update script

Homebrew/mas-tap.rb, script/bottle
Fixed the following error from the `bottle` script:
> fatal: Unable to create '/Users/ben/Library/Caches/org.carthage.CarthageKit/dependencies/Commandant/./index.lock': Operation not permitted
=> 🍼 Update formula for 1.6.3

README.md
`brew tap-pin` command is now deprecated.
=> 💡 Update readme with simpler tap usage

contrib/completion/mas.fish
* Suggestions for `mas upgrade`
* Including version info from `mas outdated`
* Suggestions for `mas uninstall` that are live (instead of only being accurate at startup)
* Suggestions for [`home` `info` `install` `open` `vendor`] that runs `mas search`
* You can for example type `mas install uly` and it will complete to `mas install ulysses`
* Added `mas help` completions for all commands
A lot of this is grabbed from, improved from, and inspired by my personal [fish-mas-completions](https://github.com/lwolfsonkin/fish-mas-completions) repo, but this is a much better place for them.
=> Seriously more interactive fish completions

script/build
Small change so that DerivedData path is the same as when using Xcode.
=> 📜 Build workspace instead of project

Brewfile.lock.json, CHANGELOG.md, MasKit/Formatters/AppListFormatter.swift, MasKitTests/Formatters/AppListFormatterSpec.swift, mas-cli.xcodeproj/project.pbxproj
PR #87 improved the `list` command output by aligning the name and version fields vertically. However, a last-minute change to address `brew bundle` compatibility left these columns misaligned.
```
↪ mas list
549083868  Display Menu               (2.2.3)
1477385213  Save to Pocket             (1.1)
904280696  Things                     (3.12.6)
1333542190  1Password 7                (7.6)
883878097  Server                     (5.10)
```
This PR fixes the alignment as shown below.
```
↪ mas list
549083868   Display Menu               (2.2.3)
1477385213  Save to Pocket             (1.1)
904280696   Things                     (3.12.6)
1333542190  1Password 7                (7.6)
883878097   Server                     (5.10)
```
=> 🐛 Fix alignment of 2nd column of list command output

.gitignore, CHANGELOG.md, Homebrew/mas-tap.rb, Homebrew/mas.rb, mas-cli.xcodeproj/project.pbxproj, script/version
=> 🔖 Release 1.7.1

.editorconfig, Homebrew/mas-tap.rb, Homebrew/mas.rb, script/bottle, script/brew_formula_update, script/brew_update, script/build_artifacts
Pending bottle hashes from Homebrew/homebrew-core#60752
=> 🍺 Formula 1.7.1

CHANGELOG.md, Cartfile.resolved, Carthage/Checkouts/Quick/Package@swift-5.3.swift, Carthage/Checkouts/Quick/Quick.podspec, Carthage/Checkouts/Quick/Sources/QuickObjCRuntime/include/QuickObjCRuntime.h, Gemfile.lock, mas-cli.xcodeproj/project.pbxproj
- ✨ Support for Apple Silicon (arm64) #310  
thanks, [@chris-araman](https://github.com/chris-araman)!
- ⚒️ Xcode 12.2 and macOS 10.15.4 required to build
- 🕊 Swift 5.2 #310
- ⚒️ Xcode 11.4 and macOS 10.15.2 required to build
- 🐛 Specify desired `LD_RUNPATH_SEARCH_PATHS` at link-time #310
- 🐛 Default PREFIX to /opt/homebrew on Apple Silicon (arm64)
- ⬆️ Commandant (0.18.0) #310
- ⬆️ Nimble (9.0.0) #310
- ⬆️ Quick (3.1.0) #310
- 🎨 Improve `mas list` command output #278  
thanks, [@danielbayley](https://github.com/danielbayley)!
- 🐛 Fix alignment of 2nd column of list command output #298
- ✨ `Makefile` #277
=> 🔖 Release 1.8

CHANGELOG.md, MasKit/Commands/Outdated.swift, MasKit/Commands/Upgrade.swift, MasKit/Formatters/Utilities.swift
Fix outdated & upgrade commands.
Resolves #111 #245 #248 #252 #282 #306
Possibly #76 #92 #247 #249 #290
=> Fix outdated & upgrade commands

Brewfile.lock.json, Gemfile.lock, mas-cli.xcodeproj/project.pbxproj, script/bootstrap, script/version
Little hotfix to fix outdated & upgrade commands #312
=> 🔖 Release 1.8.1

MasKit/Commands/List.swift, mas-cli.xcodeproj/project.pbxproj
Regressed in 83a1da9df751ee012ba798d6713596904c77272a which undid #278. So, it appears that this improvement never made it out in v1.8.0. 😕
Affects #298
Found while reviewing #334
=> 🐛 Restore AppListFormatter

script/bottle
Made the `bottle` script smarter using `uname -m` and `sw_vers -productVersion` to pick between `arm64_big_sur`, `big_sur` and `catalina`.
```
↪ script/bottle
CURRENT_OS_VERSION_MAJOR: 11
CURRENT_OS_VERSION_MINOR: 2
CURRENT_PLATFORM: big_sur
Unlinking /usr/local/Cellar/mas/1.8.1... 0 symlinks removed.
==> 🍼 Bottling mas 1.8.1 for: arm64_big_sur big_sur catalina mojave high_sierra sierra el_capitan
Warning: mas 1.8.1 is already installed, it's just not linked.
To link this version, run:
brew link mas
git config --replace-all homebrew.devcmdrun true
==> Bottling mas--1.8.1.big_sur.bottle.tar.gz...
tar cf /Users/phatblat/dev/mas-cli/mas/mas--1.8.1.big_sur.bottle.tar mas/1.8.1
gzip -f mas-bottle.tar
==> Detecting if mas--1.8.1.big_sur.bottle.tar.gz is relocatable... …
```
=> 💪🏼 Add arm64_big_sur to bottle script

MasKit/Network/NetworkManager.swift
Fixes #328 and #337.
The default shared `URLSession` stores a cache in `~/Library/Caches/com.mphys.mas-cli/`. I don't think users expect `mas` to store any local state, so it should be safe to clean this up.
=> 🪣 Use an ephemeral session

.github/dependabot.yml
It'll create pull requests with updates saving us a little time. So far, it only supports Ruby Gem Bundler and not Homebrew (or mas!) packages, but it's a start.
=> 🤖 Configure Dependabot to update Ruby Gems

README.md
- Clarify limitations of running on macOS 10.11 through 10.14.3.
- Remove "build from source" as an option for older macOS releases, as Xcode 12 is now required and it requires macOS 10.15.4.
- Clarify that `script/bootstrap` is required before initial `script/build`.
- 🪦🎶 RIP iTunes
- Add instructions for running tests.
=> 📄 Update README

Sources/MasKit/Formatters/Utilities.swift
Unfortunately, the hack for `OutputListener` broke `clearLine` and color output. We don't have a way to pass the variadic arguments directly to `Swift.print` due to a [language limitation](https://bugs.swift.org/browse/SR-128).
This change fixes progress output from `mas upgrade` and color output from `printInfo`, `printWarning`, and `printError`. Additionally, we now override `print` only for debug builds.
I've verified line clearing and color output by inserting the following into `OutdatedCommand`:
```
print("Downloading foo", terminator: "")
clearLine()
print("Downloading bar", terminator: "")
clearLine()
print("Downloading baz")
printInfo("Complete")
```
=> 🖨 Override print only in debug builds

Tests/MasKitTests/OutputListenerSpec.swift
I only just realized that these haven't been running due to the existing use of `xdescribe`.
=> 💡 Turn on the OutputListener tests

CONTRIBUTING.md, Dangerfile, README.md, docs/style.md
=> 🪧 Update references to main branch

Homebrew/mas-tap.rb, Homebrew/mas.rb, script/bottle
I figured out that Homebrew [supports](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/github_releases.rb) downloading bottles from GitHub Releases. No need to figure out how to talk to ghcr.io!
We can build `script/bottles` and upload the results from `.build/bottles` as release assets. I've already done this for [v1.8.2](https://github.com/mas-cli/mas/releases/tag/v1.8.2).
=> 🍺 Publish bottles for custom tap to GitHub Releases

Sources/MasKit/Controllers/MasAppLibrary.swift
Fixes #250 and #309.
This seems like a reasonable approach, as the Mac App Store app [assumes](https://apple.stackexchange.com/a/19898) applications are always installed to `/Applications/` and not `~/Applications/` or elsewhere.
I've verified that after moving `/Applications/Microsoft PowerPoint.app` to `~/Downloads/`:
- `mas list` no longer shows PowerPoint
- `mas upgrade 462062816` yields `Warning: Nothing found to upgrade`
- `mas install 462062816` downloads it to `/Applications/` again
=> 🏡 Ignore applications moved outside the system Applications folder

Dangerfile, Package.resolved, Package.swift
=> ⬆️ Nimble (9.2.0)

Brewfile, Brewfile.lock.json, Gemfile.lock, Package.resolved, Package.swift
Nimble [9.2.1](https://github.com/Quick/Nimble/releases/tag/v9.2.1) included some fixes for Xcode 13.
I also removed `swiftenv` for the time being, as it's currently unused by our scripts and it does not include an arm64 build, causing `script/bootstrap` to fail.
=> Prepare for Xcode 13

Homebrew/mas-tap.rb, Homebrew/mas.rb, script/bottle
Just updating the local copy of our Homebrew formula.
=> 🍺 Homebrew formula for 1.8.3

Package.resolved, Package.swift
Just keeping up rather than catching up. The `pk7` branch still has the PromiseKit 7 WIP. Swift 5.5 async/await still requires macOS 12.
=> ⬆️ PromiseKit (6.16.0)

Sources/MasKit/AppStore/Downloader.swift, Sources/MasKit/Commands/Open.swift, Sources/MasKit/Formatters/Utilities.swift, Sources/MasKit/Models/SoftwareProduct.swift, Sources/mas/main.swift, Tests/MasKitTests/Models/SoftwareProductSpec.swift
=> ⚠️ Add a temporary warning about macOS Monterey

README.md, Sources/MasKit/AppStore/Downloader.swift, Sources/MasKit/AppStore/SSPurchase.swift, Sources/MasKit/Commands/Account.swift, Sources/MasKit/Commands/Purchase.swift, Sources/MasKit/Commands/SignIn.swift, Sources/MasKit/Errors/MASError.swift, Sources/mas/main.swift
This change:
- disables the `account` command on macOS 12
- #417
- disables the `purchase` command on macOS 10.15
- #289
- documents why some commands are disabled on some macOS versions
- #164
- documents why the App Store app and `mas` don't always agree on which apps are outdated, and...
- #384
- #387
- 🥁 fixes `install`, `lucky`, and (I believe 🤞🏼) `upgrade` for existing purchases on macOS 12 🥳 
- removes the warning added in 1.8.4 about functionality on macOS 12
=> 🐛 Allow redownloads on macOS 12 Monterey

Sources/MasKit/Controllers/StoreSearch.swift, Tests/MasKitTests/Controllers/StoreSearchSpec.swift
Teaches `mas` to pass the user's ISO region code to the iTunes Search API, allowing users to find apps that are not available in the United States.
Caveat: CommerceKit and StoreFoundation don't seem to expose the region of the Apple ID signed into the App Store. Instead, we'll make an educated guess that it matches the currently selected locale in macOS. This obviously isn't always going to match, but it's probably better than passing no "country" at all to the iTunes Search API.
Fixes #442 and #85.
=> 🌍 Localize queries

.github/CODEOWNERS, .github/workflows/build-test.yml, Brewfile.lock.json, script/test
GitHub Actions only support "X64" architecture right now, so the [current solution](https://gregmfoster.medium.com/using-m1-mac-minis-to-power-our-github-actions-ios-ci-540c55af13ea) relies on Rosetta 2. Xcode builds (at least running XCUITests) require `arch -arm64` prefixed to the commands, but it seems that Swift build & test do not.
Fixes #380 
Scripts in https://github.com/mas-cli/m1-github-actions-runner
```
↪ ./start.sh
--------------------------------------------------------------------------------
|        ____ _ _   _   _       _          _        _   _                      |
|       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
|      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
|      | |_| | | |_|  _  | |_| | |_) |  / …
```
=> 👷🏻‍♂️ Switch to self-hosted M1 Mac mini runner

Sources/MasKit/Errors/MASError.swift
The corresponding section header starts with "⚠️", which needs to be
encoded in the link. Otherwise, the anchor doesn't work.
=> 🐛 Fix link to known issues

Makefile, script/install
While generating the `.pkg` for #450 it appears that current versions of Swift output binaries to a different subfolder under `.build/`. Also added dependencies to a couple of make targets to ensure things are run in the correct order.
=> 📜 Script fixes

README.md
The current documentation states that the build directory is called `build`, while in reality it is `.build`, which can lead to confusion amongst people new to the project. This PR corrects the folder name in `README.md`.
=> Corrected the build folder name

Package.resolved, Sources/MasKit/Commands/Account.swift, Sources/MasKit/Commands/Home.swift, Sources/MasKit/Commands/Info.swift, Sources/MasKit/Commands/List.swift, Sources/MasKit/Commands/Lucky.swift, Sources/MasKit/Commands/Open.swift, Sources/MasKit/Commands/Outdated.swift, Sources/MasKit/Commands/Search.swift, Sources/MasKit/Commands/Vendor.swift, Sources/MasKit/Formatters/Utilities.swift, Tests/MasKitTests/Commands/OutdatedCommandSpec.swift
Cleanup of error messages.
- Removed some duplicate error messages
- All errors printed to `stderr` now
- Added `--verbose` flag to `outdated` command. Warnings about apps removed from the App Store will only be shown when flag provided.
```
❯ mas outdated
803453959 Slack (4.28.182 -> 4.28.184)
1055511498 Day One (7.16 -> 7.17)
❯ mas outdated --verbose
Warning: Identifier 883878097 not found in store. Was expected to identify Server.
Warning: Identifier 1125131804 not found in store. Was expected to identify Later.
Warning: Identifier 588726889 not found in store. Was expected to identify ReadKit.
Warning: Identifier 980258689 not found in store. Was expected to identify SSDReporter.
Warning: Identifier 927292435 not found in store. Was expected to identify iStat Mini.
Warning: Identifier …
```
=> 🔇 Error message cleanup

.github/workflows/build-test.yml, Package.swift, Sources/MasKit/AppStore/Downloader.swift, Sources/MasKit/AppStore/SSPurchase.swift, Sources/MasKit/Commands/Outdated.swift, Sources/MasKit/Commands/Uninstall.swift, Sources/MasKit/Controllers/MasStoreSearch.swift, Sources/MasKit/Controllers/StoreSearch.swift, Sources/MasKit/Errors/MASError.swift, Sources/MasKit/Formatters/AppInfoFormatter.swift, Sources/MasKit/Formatters/AppListFormatter.swift, Sources/MasKit/Formatters/SearchResultFormatter.swift, Sources/MasKit/Formatters/Utilities.swift, Sources/MasKit/Network/URLSession+NetworkSession.swift, Tests/MasKitTests/Network/NetworkSessionMock.swift, Tests/MasKitTests/Nimble/ResultPredicates.swift
Pulling @rgoldberg changes from https://github.com/mas-cli/mas/pull/508.
=> Apple silicon GitHub hosted runner

.github/workflows/build-test.yml, Package.swift, Sources/MasKit/AppStore/Downloader.swift, Sources/MasKit/AppStore/SSPurchase.swift, Sources/MasKit/Commands/Outdated.swift, Sources/MasKit/Commands/Uninstall.swift, Sources/MasKit/Controllers/MasStoreSearch.swift, Sources/MasKit/Controllers/StoreSearch.swift, Sources/MasKit/Errors/MASError.swift, Sources/MasKit/Formatters/AppInfoFormatter.swift, Sources/MasKit/Formatters/AppListFormatter.swift, Sources/MasKit/Formatters/SearchResultFormatter.swift, Sources/MasKit/Formatters/Utilities.swift, Sources/MasKit/Network/URLSession+NetworkSession.swift, Tests/MasKitTests/Network/NetworkSessionMock.swift, Tests/MasKitTests/Nimble/ResultPredicates.swift
Apple Silicon Github-hosted runner for build-test job.
See https://github.com/mas-cli/mas/pull/496#issuecomment-1918093826
=> Apple Silicon Github-hosted runner for build-test job

Sources/MasKit/Controllers/StoreSearch.swift
Attempt to fix #491, #336 (and some other dup issue)
This idea is from [https://github.com/mangerlahn/Latest](https://github.com/mangerlahn/Latest/blob/9e98e7317926597d98d323c43a562d6caeca21c7/Latest/Model/Update%20Checker%20Extensions/MacAppStoreCheckerOperation.swift#L114-L127)(Thanks!). They also added "macSoftware" param, which I believe is unnecessary for us as it is not possible to upgrade an iOS-only app from command-line. (Not 100% sure, if that causes problem, we can add the param in the future)
=> 🔧 Check for mac updates only

Sources/MasKit/Controllers/MasStoreSearch.swift
Fix breaking lint issue in `MasStoreSearch.swift` in `main`.
Resolve #546
=> Fix breaking lint issue in MasStoreSearch.swift.

README.md, Sources/MasKit/Commands/Purchase.swift, Tests/MasKitTests/Commands/PurchaseCommandSpec.swift
`purchase` seems to work on macOS 12+. It was probably never broken. It was just misunderstood to allow purchasing of non-free apps, but that wasn't the case.
Resolve #289
=> Re-enable `purchase`.

Sources/MasKit/Models/SearchResult.swift, Sources/MasKit/Models/SoftwareProduct.swift, Tests/MasKitTests/Models/SoftwareProductSpec.swift
`outdated` checks if new app version requires newer macOS for all kinds of apps, not just mac-software
Resolve #540
=> `outdated` checks if new app version requires newer macOS for all kinds of apps, not just mac-software

Sources/mas/AppStore/Downloader.swift, Sources/mas/AppStore/SSPurchase.swift, Sources/mas/Commands/Home.swift, Sources/mas/Commands/Info.swift, Sources/mas/Commands/Install.swift, Sources/mas/Commands/Lucky.swift, Sources/mas/Commands/Open.swift, Sources/mas/Commands/Outdated.swift, Sources/mas/Commands/Purchase.swift, Sources/mas/Commands/Uninstall.swift, Sources/mas/Commands/Upgrade.swift, Sources/mas/Commands/Vendor.swift, Sources/mas/Controllers/AppLibrary.swift, Sources/mas/Controllers/MasStoreSearch.swift, Sources/mas/Controllers/StoreSearch.swift, Sources/mas/Formatters/AppListFormatter.swift, Sources/mas/Formatters/SearchResultFormatter.swift, Sources/mas/Mas.swift, Sources/mas/Models/SearchResult.swift, Tests/masTests/Commands/HomeSpec.swift, Tests/masTests/Commands/InfoSpec.swift, Tests/masTests/Commands/OpenSpec.swift, Tests/masTests/Commands/UninstallSpec.swift, Tests/masTests/Commands/VendorSpec.swift, Tests/masTests/Controllers/MasStoreSearchSpec.swift, Tests/masTests/Controllers/StoreSearchMock.swift
Use `typealias AppID = UInt64` for all app ID types.
Standardize all variables & parameter names for app IDs.
Resolve #478
=> Fix app IDs

Sources/mas/Commands/Home.swift, Sources/mas/Commands/Info.swift, Sources/mas/Commands/Open.swift, Sources/mas/Commands/Search.swift, Sources/mas/Commands/Vendor.swift, Sources/mas/Controllers/MasStoreSearch.swift, Sources/mas/Controllers/StoreSearch.swift, Tests/masTests/Controllers/MasStoreSearchSpec.swift
There are numerous problems with the integration with the iTunes Search API.
1. Add & use `Entity.desktopSoftware` instead of `macSoftware`. Former returns info (including version & description) that aligns with what is displayed in the App Store, while latter is at least sometimes out of alignment. Latter also seems to return any software that can run on a Mac (e.g., iOS, iPadOS, etc. software for Apple Silicon), seeming to default to iOS info. Probably better to get versions for each platform separately so we know what's for what platform.
2. Update iTunes Search API documentation URL to https://performance-partners.apple.com/search-api.
3. Add `media=software` query item to lookup URL to improve results.
4. Refactor `StoreSearch.lookup(…)` & `StoreSearch.search(…)` to share …
=> Fix iTunes Search API issues

Sources/mas/Commands/Outdated.swift, Sources/mas/Commands/Upgrade.swift, Sources/mas/Mas.swift
`appIDValue` to encapsulate `uint64Value`.
Resolve #574
=> `appIDValue` to encapsulate `uint64Value`.

Package.resolved, Package.swift, Tests/masTests/Commands/AccountSpec.swift, Tests/masTests/Commands/HomeSpec.swift, Tests/masTests/Commands/InfoSpec.swift, Tests/masTests/Commands/InstallSpec.swift, Tests/masTests/Commands/ListSpec.swift, Tests/masTests/Commands/LuckySpec.swift, Tests/masTests/Commands/OpenSpec.swift, Tests/masTests/Commands/OutdatedSpec.swift, Tests/masTests/Commands/PurchaseSpec.swift, Tests/masTests/Commands/ResetSpec.swift, Tests/masTests/Commands/SearchSpec.swift, Tests/masTests/Commands/SignInSpec.swift, Tests/masTests/Commands/SignOutSpec.swift, Tests/masTests/Commands/UninstallSpec.swift, Tests/masTests/Commands/UpgradeSpec.swift, Tests/masTests/Commands/VendorSpec.swift, Tests/masTests/Commands/VersionSpec.swift, Tests/masTests/Controllers/MasAppLibrarySpec.swift, Tests/masTests/Controllers/MasStoreSearchSpec.swift, Tests/masTests/ExternalCommands/OpenSystemCommandSpec.swift, Tests/masTests/Formatters/AppListFormatterSpec.swift, Tests/masTests/Formatters/SearchResultFormatterSpec.swift, Tests/masTests/Models/SearchResultListSpec.swift, Tests/masTests/Models/SearchResultSpec.swift, Tests/masTests/Models/SoftwareProductSpec.swift
Downgrade Nimble & Quick to fix testing on newer Xcode versions.
Resolve #583
=> Downgrade Nimble & Quick to fix testing on newer Xcode versions.

.github/workflows/build-test.yml, Brewfile, script/bootstrap, script/lint
Improve GitHub runners:
- Upgrade GitHub runners from `macos-14` to `macos-15`.
- Suppress useless `swiftformat` output on GitHub runners.
- Change Swift bird emoji to ensure consistent spacing.
- Install `swiftlint` & `peripheryapp/periphery` tap via `Brewfile` iff macOS >= 13 (install breaks on macOS <= 12).
Resolve #594
=> Improve GitHub runners

Package.resolved, Package.swift, Sources/mas/Formatters/AppInfoFormatter.swift
Additional improvements enabled by macOS 10.13:
- Upgrade PromiseKit to 8.1.2 (current)
- Use `ISO8601DateFormatter`
Resolve #613
=> Additional improvements enabled by macOS 10.13

Sources/mas/Commands/Open.swift, Tests/masTests/Commands/OpenSpec.swift
Open the Mac App Store without any spurious error dialogs.
Use PromiseKit properly.
Don't use `OpenCommand`.
Resolve #217
=> Open the Mac App Store without any spurious error dialogs.

Sources/mas/Network/URL.swift
Simplify `open()` extension func for `URL`.
=> Simplify `open()` extension func for `URL`.

Sources/mas/Controllers/AppStoreSearcher.swift, Sources/mas/Controllers/ITunesSearchAppStoreSearcher.swift
=> Fix typos in DocC

.swift-format, .swiftformat, .swiftlint.yml, Sources/mas/AppStore/PurchaseDownloadObserver.swift, Tests/masTests/.swift-format
Improve downloading output.
Update linting for access control on extensions.
Resolve #307
=> Improve downloading output

.github/ISSUE_TEMPLATE/01-bug-report.yml, .github/ISSUE_TEMPLATE/02-feature-request.yml, README.md
Improve GitHub issue forms: add console block formatting, Processor input, headers, and cleanup placeholders, etc.
Improve `README.md` code block types.
Resolve #661
=> Improve GitHub web pages

.github/ISSUE_TEMPLATE/01-bug-report.yml, .github/ISSUE_TEMPLATE/02-feature-request.yml
Update GitHub Issue Form spacing to avoid format violations.
Resolve #664
=> Update GitHub Issue Form spacing to avoid format violations

Sources/mas/Commands/Install.swift, Sources/mas/Commands/Lucky.swift, Sources/mas/Commands/Outdated.swift, Sources/mas/Commands/Purchase.swift, Sources/mas/Commands/Uninstall.swift, Sources/mas/Commands/Upgrade.swift, Sources/mas/Formatters/AppListFormatter.swift, Sources/mas/Models/SearchResult.swift, Sources/mas/Models/SoftwareProduct.swift
Replace `appNameOrBundleIdentifier` & all output `appName` with `displayName`, which provides better fallback values for the app name.
Minor code cleanup.
Resolve #480
=> Replace `appNameOrBundleIdentifier` & all output `appName` with `displayName`

.github/workflows/codeql.yml
Scan for security vulnerabilities with GitHub CodeQL by adding `.github/workflows/codeql.yml` workflow.
Resolve #645
=> Scan for security vulnerabilities with GitHub CodeQL

.github/ISSUE_TEMPLATE/01-bug-report.yml, .github/workflows/codeql.yml, Sources/mas/Commands/Config.swift, script/lint, script/test
- Improve `mas config`:
- Reorder `mas config` output.
- Set `Package.installMethod` from `script/lint` & `script/test`.
- Simplify & consolidate `sysctl` value reading for `mas config`.
- Improve Bug Report form text.
- Only run CodeQL for the `main` branch.
Resolve #701
=> Cleanup 1.9.0

script/version
Use `MAS_DIRTY_INDICATOR` environment variable to set the dirty workspace indicator for the version output by `script/version`.
Resolve #703
=> Use `MAS_DIRTY_INDICATOR` environment variable to set the dirty workspace indicator for the version output by `script/version`

Sources/mas/Controllers/ITunesSearchAppStoreSearcher.swift
Do not scrape MAS app web page for version.
Resolve #707
=> Do not scrape MAS app web page for version

script/_setup_script, script/clean
Use `builtin` instead of `\` in scripts.
Improve logging emoji spacing.
Resolve #715
=> Improve scripts

.swift-format, Brewfile, Tests/masTests/.swift-format, script/format, script/lint, script/test, script/version
Improve `script/test` boilerplate filtering for newer `swift` executables.
Resolve #731
=> Improve `script/test` boilerplate filtering for newer `swift` executables.

Package.resolved, Package.swift
Downgrade Quick to 7.5.0 to fix multi-architecture executable build bug in Quick 7.6.0+.
Resolve #748
=> Downgrade Quick to 7.5.0 to fix multi-architecture executable build bug in Quick 7.6.0+

script/version
Do not prepend any branch prefix to the version if the main branch does not exist.
Resolve #751
=> Do not prepend any branch prefix to the version if the main branch does not exist

.github/dependabot.yml
Ignore major & minor updates for Quick in Dependabot since we're stuck on old Quick 7.5.x until 7.6+ is fixed.
=> Ignore major & minor updates for Quick in Dependabot

.github/dependabot.yml
Enable Dependabot checks for Quick.
Resolve #762
=> Enable Dependabot checks for Quick

.swiftlint.yml, Sources/mas/AppStore/CKSoftwareProduct+SoftwareProduct.swift, Sources/mas/AppStore/Downloader.swift, Sources/mas/AppStore/PurchaseDownloadObserver.swift, Sources/mas/Commands/Account.swift, Sources/mas/Commands/Info.swift, Sources/mas/Commands/Install.swift, Sources/mas/Commands/Lucky.swift, Sources/mas/Commands/Outdated.swift, Sources/mas/Commands/Purchase.swift, Sources/mas/Commands/Search.swift, Sources/mas/Commands/SignIn.swift, Sources/mas/Commands/Upgrade.swift, Sources/mas/Controllers/AppLibrary.swift, Sources/mas/Controllers/SpotlightSoftwareMap.swift, Sources/mas/Errors/MASError.swift, Sources/mas/Formatters/AppInfoFormatter.swift, Sources/mas/Formatters/AppListFormatter.swift, Sources/mas/Formatters/Utilities.swift, Sources/mas/Models/SimpleSoftwareProduct.swift, Sources/mas/Models/SoftwareProduct.swift, Sources/mas/Network/NetworkManager.swift, Tests/masTests/.swiftlint.yml, Tests/masTests/Commands/OutdatedSpec.swift, Tests/masTests/Commands/UninstallSpec.swift, Tests/masTests/Formatters/AppListFormatterSpec.swift, Tests/masTests/Models/SoftwareProductSpec.swift
Code cleanup:
- Use `appID: AppID` instead of `itemIdentifier: NSNumber`
- Set handlers to `nil` in `PurchaseDownloadObserver`
- Improve download retry warning
- Improve SwiftLint config
- Improve syntax
- Improve variable names
Resolve #775
=> Code cleanup

Sources/mas/Controllers/SpotlightSoftwareMap.swift
Use `NSMetadataItem*Key` instead of `kMDItem*` for Spotlight query keys.
Resolve #792
=> Use `NSMetadataItem*Key` instead of `kMDItem*` for Spotlight query keys

Sources/mas/Commands/List.swift, Tests/masTests/Commands/ListSpec.swift
Warn about how to index installed apps when no apps found by `mas list`.
Resolve #809
=> Warn about how to index installed apps when no apps found by `mas list`

Brewfile
Always install all dependencies in `Brewfile` as now only support building on macOS 13+.
Resolve #823
=> Always install all dependencies in `Brewfile` as now only support building on macOS 13+

Sources/mas/Formatters/AppInfoFormatter.swift
Use local time zone for `info` dates.
Related date & DocC cleanup.
Resolve #825
=> Use local time zone for `info` dates

Sources/mas/Errors/MASError.swift
Improve `MASError.notSupported` description.
Resolve #827
=> Improve `MASError.notSupported` description

Sources/mas/Network/NetworkManager.swift
Do not delete the cache folder since it hasn't been used since 2021.
Resolve #833
=> Do not delete the cache folder since it hasn't been used since 2021

Sources/mas/Controllers/SpotlightInstalledApps.swift
Only interact with apps under `/Applications` or MAS-designated large app drive.
Resolve #832
=> Only interact with apps under `/Applications` or MAS-designated large app drive

Sources/mas/Commands/Home.swift, Sources/mas/Commands/Info.swift, Sources/mas/Commands/Lucky.swift, Sources/mas/Commands/Search.swift, Sources/mas/Commands/Uninstall.swift, Sources/mas/Commands/Vendor.swift, Sources/mas/Errors/MASError.swift, Tests/masTests/Commands/UninstallSpec.swift
Support multiple app ID & search term arguments for all relevant commands.
Resolve #225
=> Support multiple app ID & search term arguments for all relevant commands

README.md
Improve README shields.
Resolve #858
=> Improve README shields

Sources/mas/AppStore/PurchaseDownloadObserver.swift, Sources/mas/Commands/Upgrade.swift, Sources/mas/Formatters/AppListFormatter.swift, Sources/mas/Formatters/SearchResultFormatter.swift, Tests/masTests/Formatters/AppListFormatterSpec.swift, Tests/masTests/Formatters/SearchResultFormatterSpec.swift, docs/sample.swift
Improve Swift comments & `sample.swift`.
Resolve #860
=> Improve Swift comments & `sample.swift`

Sources/mas/AppStore/Downloader.swift, Sources/mas/AppStore/SSPurchase.swift, Sources/mas/Commands/Config.swift, Sources/mas/Commands/Lucky.swift, Sources/mas/Commands/Upgrade.swift, Sources/mas/Controllers/SpotlightInstalledApps.swift, Sources/mas/Formatters/AppInfoFormatter.swift, Sources/mas/Models/InstalledApp.swift, Tests/masTests/Commands/InfoSpec.swift, Tests/masTests/Commands/OutdatedSpec.swift, Tests/masTests/Commands/SearchSpec.swift, Tests/masTests/Models/SearchResultListSpec.swift, Tests/masTests/Models/SearchResultSpec.swift
Improve Swift spacing & minor Swift cleanup.
Resolve #867
=> Improve Swift spacing & minor Swift cleanup

Scripts/_setup_script, Scripts/bootstrap, Scripts/build, Scripts/clean, Scripts/format, Scripts/lint, Scripts/package, Scripts/release_cancel, Scripts/release_start, Scripts/test
Color script start header arrow blue iff tty.
Resolve #886
=> Color script start header arrow blue iff tty

Scripts/test
Update `Scripts/test` boilerplate output filtering.
Resolve #889
=> Update `Scripts/test` boilerplate output filtering

.swiftformat, Scripts/format, Scripts/lint, Sources/mas/AppStore/PurchaseDownloadObserver.swift
Update linting & formatting; rename Swift function parameter.
Resolve #905
=> Update linting & formatting; rename Swift function parameter

Sources/mas/AppStore/Downloader.swift, Sources/mas/AppStore/PurchaseDownloadObserver.swift, Sources/mas/AppStore/SSPurchase.swift, Sources/mas/Commands/Install.swift, Sources/mas/Commands/Lucky.swift, Sources/mas/Commands/Open.swift, Sources/mas/Commands/OptionGroups/AppIDsOptionGroup.swift, Sources/mas/Commands/Outdated.swift, Sources/mas/Commands/Purchase.swift, Sources/mas/Commands/Uninstall.swift, Sources/mas/Commands/Upgrade.swift, Sources/mas/Controllers/ITunesSearchAppStoreSearcher.swift, Sources/mas/Controllers/SpotlightInstalledApps.swift, Sources/mas/Errors/MASError.swift, Sources/mas/Formatters/AppListFormatter.swift, Sources/mas/Models/AppID.swift, Sources/mas/Models/InstalledApp.swift, Sources/mas/Models/SearchResult.swift, Tests/masTests/Commands/HomeTests.swift, Tests/masTests/Commands/InfoTests.swift, Tests/masTests/Commands/OpenTests.swift, Tests/masTests/Commands/OutdatedTests.swift, Tests/masTests/Commands/SearchTests.swift, Tests/masTests/Commands/UninstallTests.swift, Tests/masTests/Commands/VendorTests.swift, Tests/masTests/Controllers/ITunesSearchAppStoreSearcherTests.swift, Tests/masTests/Formatters/AppListFormatterTests.swift, Tests/masTests/Models/InstalledAppTests.swift
Accept Bundle IDs as arguments alongside ADAM IDs (fka app IDs).
No longer accept app names as arguments for `upgrade`.
Resolve #541
=> Accept Bundle IDs as arguments alongside ADAM IDs (fka app IDs)

.swiftlint.yml, Sources/mas/Commands/Reset.swift
Refactor `Reset` to terminate processes using C APIs, instead of running the `killall` shell command via a Swift `Process`.
Terminate processes by full executable path instead of by executable name.
Terminate `com.apple.dock` & `com.apple.storeuid` as applications instead of as processes.
No longer terminate `ContextStoreAgent`.
Resolve #667
=> Refactor `Reset`

Sources/MAS/Commands/Lucky.swift, Sources/MAS/Controllers/AppStoreSearcher.swift, Sources/MAS/Controllers/ITunesSearchAppStoreSearcher.swift
Misc Swift cleanup.
Resolve #970
=> Misc Swift cleanup

.swiftformat, Sources/mas/Commands/Home.swift, Sources/mas/Commands/Open.swift, Sources/mas/Commands/Vendor.swift, Sources/mas/Formatters/AppInfoFormatter.swift, Sources/mas/Formatters/SearchResultFormatter.swift, Sources/mas/Models/SearchResult.swift, Sources/mas/Models/SearchResultList.swift, Tests/MASTests/Commands/MASTests+Info.swift, Tests/MASTests/Commands/MASTests+Outdated.swift, Tests/MASTests/Commands/MASTests+Search.swift, Tests/MASTests/Controllers/MASTests+ITunesSearchAppStoreSearcher.swift, Tests/MASTests/Controllers/MockAppStoreSearcher.swift, Tests/MASTests/Formatters/MASTests+SearchResultFormatter.swift, Tests/MASTests/Models/MASTests+SearchResult.swift
Refactor `SearchResult` & `SearchResultList` to use model-oriented let properties instead of JSON-oriented var properties.
Resolve #895
=> Refactor `SearchResult` & `SearchResultList` to use model-oriented let properties instead of JSON-oriented var properties
