- README.md
- mas-cli/Commands/SignIn.swift
> Use password prompt instead of passing directly

- mas-cli/Error.swift
- mas-cli/NSURLSession+Synchronous.swift
I've found some small things while reading the code, don't want to make a huge PR, decided start with tiny one.
@rodionovd @argon please review 😃
> Update small bits of code to make them more swift (3) like

- mas-cli/AppStore/Downloader.swift
- mas-cli/AppStore/ISStoreAccount.swift
- mas-cli/AppStore/PurchaseDownloadObserver.swift
- mas-cli/Commands/Install.swift
- mas-cli/Commands/Search.swift
Hey @rodionovd, sorry for splitting swiftyfying in two PRs, but looks like it is final version.
> Swiftify rest of the code

- README.md
> Add details about Homebrew integration

- .bundle/config
- .gitignore
- .travis.yml
- mas-cli.xcodeproj/project.pbxproj
- mas-cli.xcodeproj/xcshareddata/xcschemes/mas-cli.xcscheme
- script/build
- script/package
Attempting to resolve travis build issues with `xcpretty` that are affecting #88.
> Resolve build issues

- .travis.yml
Updating to [xcode9.2](https://docs.travis-ci.com/user/reference/osx/#Xcode-9.2) to address build issues in #114
> Update travis image to xcode9.2

- README.md
[![Build Status](https://travis-ci.org/mas-cli/mas.svg?branch=master)](https://travis-ci.org/mas-cli/mas)
> Add build badge to readme

- Homebrew/mas.rb
Add homebrew formula for easy reference.
>  🍺 Homebrew

- Homebrew/mas.rb
> Update copy of formula after bottles were built

- .travis.yml
- CHANGELOG.md
Updated Xcode project and travis CI image
> ⬆️🛠 Xcode 9.4

- README.md
[![Build Status](https://travis-ci.com/mas-cli/mas.svg?branch=master)](https://travis-ci.com/mas-cli/mas)
> 🔗 Update build badge to point to travis-ci.com

- .travis.yml
- CHANGELOG.md
- Homebrew/mas-tap.rb
- Homebrew/mas.rb
- mas-cli.xcodeproj/project.pbxproj
Update project files to use Xcode 10 and Swift 4.2.
> 🛠 Xcode 10 & Swift 4.2

- .hound.yml
- Gemfile.lock
- Homebrew/mas-tap.rb
- Homebrew/mas.rb
- script/bottle
- script/build
- script/install
- script/package
- script/version
Tap updated in mas-cli/homebrew-tap#8
> 🍼📜 Bottle script and Formula update for 1.6.0

- CHANGELOG.md
- MasKit/Commands/Home.swift
- MasKit/Commands/Info.swift
- MasKit/Commands/Lucky.swift
- MasKit/Commands/Open.swift
- MasKit/Commands/Vendor.swift
- MasKit/Controllers/MasStoreSearch.swift
- MasKit/Controllers/StoreSearch.swift
- MasKitTests/Commands/HomeCommandSpec.swift
- MasKitTests/Commands/InfoCommandSpec.swift
- MasKitTests/Commands/VendorCommandSpec.swift
- MasKitTests/Controllers/MasStoreSearchSpec.swift
- MasKitTests/Controllers/StoreSearchMock.swift
- MasKitTests/Controllers/StoreSearchSpec.swift
> 🐛 Fix Lucky command error

- .github/ISSUE_TEMPLATE/bug_report.md
Reformat bug report template, adding checkboxes like [Carthage](https://github.com/Carthage/Carthage/blob/master/ISSUE_TEMPLATE.md)
> 📝 Revise bug report template

- CHANGELOG.md
Formatting, missing PRs and missing compare links.
> 📝 Changelog

- MasKitTests/ExternalCommands/OpenSystemCommandSpec.swift
- mas-cli.xcodeproj/project.pbxproj
> ✅ Add tests for OpenSystemCommand

- .travis.yml
- Brewfile.lock.json
- CHANGELOG.md
- Jenkinsfile
- Mintfile
- mas-cli.xcodeproj/project.pbxproj
Update CI to build project with Xcode 11.5.
> 🛠 Xcode 11.5

- Brewfile.lock.json
- CHANGELOG.md
- Homebrew/mas-tap.rb
- Homebrew/mas.rb
- MasKit/AppStore/SSPurchase.swift
- MasKit/ExternalCommands/OpenSystemCommand.swift
- script/brew_formula_update
- script/brew_release_validate
Following Homebrew/homebrew-core#55238
Finishes #274
> 🍺Formula 1.7

- MasKit/Formatters/AppInfoFormatter.swift
- MasKitTests/Commands/InfoCommandSpec.swift
> info command now outputs ISO date format

- Tests/MasKitTests/Controllers/MasAppLibrarySpec.swift
- script/test
> 🚨 Fail CI task if tests fail

- Package.resolved
- Package.swift
A follow-up to #388 and #389, with unfortunate timing. 😊
> ⬆️ PromiseKit (6.15.0)

- Brewfile.lock.json
- Gemfile.lock
- Package.resolved
- Package.swift
- Sources/mas/main.swift
> 🧹 Remove unused code

- Brewfile.lock.json
- Gemfile.lock
- Package.resolved
- Package.swift
- Sources/MasKit/Formatters/SearchResultFormatter.swift
- script/lint
> ⬆️ Periphery (2.5.2), SwiftFormat (0.48.4), Version (2.0.1)

- Brewfile.lock.json
- Homebrew/mas-tap.rb
- Homebrew/mas.rb
- script/bottle
`brew tap-unpin` doesn't seem to exist anymore.
Corresponding clarifications have already been made here:
https://github.com/mas-cli/mas/wiki/Release-Process#homebrew-custom-tap
> 🍼 Use the custom tap formula when bottling for the custom tap

- Package.resolved
- Package.swift
> ⬆️ PromiseKit (6.16.2)

- Brewfile.lock.json
- Package.resolved
- Sources/MasKit/Controllers/MasAppLibrary.swift
- Sources/MasKit/Formatters/AppListFormatter.swift
- Sources/MasKit/Formatters/SearchResultFormatter.swift
Swift does this `inout` pointer dance for us.
Also bumped deps and linted with the latest linters.
> ♻️ Simplify pointer dance

- .gitignore
Git ignore JetBrains IntelliJ IDEA config directory.
Resolve #544
> Git ignore JetBrains IntelliJ IDEA config directory.

- CONTRIBUTING.md
- Sources/MasKit/Commands/Lucky.swift
- Sources/MasKit/Controllers/AppLibrary.swift
- Sources/MasKit/Controllers/SoftwareMap.swift
- Sources/MasKit/Formatters/AppListFormatter.swift
- Sources/MasKit/Formatters/SearchResultFormatter.swift
- Tests/MasKitTests/Controllers/AppLibraryMock.swift
- docs/sample.swift
Fix typos in comments & in documentation.
Resolves #538
> Fix typos in comments & in documentation.

- Sources/MasKit/Controllers/MasStoreSearch.swift
- Sources/MasKit/Errors/MASError.swift
- Tests/MasKitTests/Errors/MASErrorTestCase.swift
Output to stderr responses from Apple endpoints that are unparsable as JSON
Resolves #536
> Output to stderr responses from Apple endpoints that are unparsable as JSON

- Brewfile
- Brewfile.lock.json
- script/uninstall
Improve usage of `trash` in scripts by using `trash -F`.
Add `trash` to `Brewfile`.
Resolve #576
> Improve usage of `trash` in scripts.

- .swiftformat
- Sources/mas/Commands/Install.swift
- Sources/mas/Commands/Lucky.swift
- Sources/mas/Commands/Purchase.swift
- Sources/mas/Commands/Uninstall.swift
- Sources/mas/Commands/Upgrade.swift
- Sources/mas/Controllers/AppLibrary.swift
- Sources/mas/Controllers/Finder.swift
- Sources/mas/Controllers/MasAppLibrary.swift
- Sources/mas/Errors/MASError.swift
- Tests/masTests/Commands/UninstallSpec.swift
- Tests/masTests/Controllers/AppLibraryMock.swift
- Tests/masTests/Errors/MASErrorTestCase.swift
> Fix `uninstall`

- Sources/mas/Commands/Account.swift
- Sources/mas/Commands/Home.swift
- Sources/mas/Commands/Info.swift
- Sources/mas/Commands/Install.swift
- Sources/mas/Commands/List.swift
- Sources/mas/Commands/Lucky.swift
- Sources/mas/Commands/Open.swift
- Sources/mas/Commands/Outdated.swift
- Sources/mas/Commands/Purchase.swift
- Sources/mas/Commands/Reset.swift
- Sources/mas/Commands/Search.swift
- Sources/mas/Commands/SignIn.swift
- Sources/mas/Commands/SignOut.swift
- Sources/mas/Commands/Uninstall.swift
- Sources/mas/Commands/Upgrade.swift
- Sources/mas/Commands/Vendor.swift
- Sources/mas/Commands/Version.swift
- contrib/completion/mas.fish
Improve help output.
Make fish shell completions more consistent with the help output.
Resolve #543
> Improve help output.

- Sources/mas/Controllers/AppStoreSearcher.swift
- Sources/mas/Controllers/ITunesSearchAppStoreSearcher.swift
- Tests/masTests/Controllers/ITunesSearchAppStoreSearcherSpec.swift
Move code from `AppStoreSearcher` to `ITunesSearchAppStoreSearcher`.
Improve DocC.
Improve Quick test names.
Resolve #607
> Refactor `AppStoreSearcher` code.

- Sources/mas/Commands/List.swift
- Sources/mas/Commands/Outdated.swift
- Sources/mas/Commands/Uninstall.swift
- Sources/mas/Commands/Upgrade.swift
- contrib/completion/mas.fish
> Cleanup help.

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Improve GitHub issue templates.
Resolve #630
> Improve GitHub issue templates

- .github/workflows/danger.yml
- .github/workflows/release-published.yml
- .github/workflows/tag-pushed.yml
- script/generate_token
- script/release_cancel
- script/release_start
Finish release overhaul from #638.
Resolve #682
> Finish release overhaul

- script/version
Append a `+` to the version name if there are any uncommitted changes or unignored untracked files.
Resolve #685
> Append a `+` to version name if there are any uncommitted changes or unignored untracked files

- Sources/mas/Commands/Outdated.swift
- Sources/mas/Commands/Upgrade.swift
- Sources/mas/Controllers/ITunesSearchAppStoreSearcher.swift
- Sources/mas/Errors/MASError.swift
- Sources/mas/Models/SearchResult.swift
- Sources/mas/Models/SoftwareProduct.swift
- Tests/masTests/Controllers/ITunesSearchAppStoreSearcherSpec.swift
- Tests/masTests/Errors/MASErrorTestCase.swift
- Tests/masTests/Models/SoftwareProductSpec.swift
Minor Swift cleanup.
Resolve #679
> Minor Swift cleanup

- .github/ISSUE_TEMPLATE/01-bug-report.yml
Improve Bug Report form.
Resolve #699
> Improve Bug Report form

- .github/workflows/build-test.yml
- .github/workflows/codeql.yml
- .github/workflows/release-published.yml
- .github/workflows/tag-pushed.yml
- script/lint
- script/setup_workflow_repo
- script/version
Include branch name in version name in certain conditions.
Resolve #705
> Include branch name in version name in certain conditions

- Sources/mas/AppStore/Downloader.swift
- Sources/mas/AppStore/ISStoreAccount.swift
- Sources/mas/AppStore/PurchaseDownloadObserver.swift
- Sources/mas/AppStore/SSPurchase.swift
- Sources/mas/Commands/Config.swift
- Sources/mas/Commands/Info.swift
- Sources/mas/Commands/Install.swift
- Sources/mas/Commands/Lucky.swift
- Sources/mas/Commands/Outdated.swift
- Sources/mas/Commands/Purchase.swift
- Sources/mas/Controllers/AppStoreSearcher.swift
- Sources/mas/Formatters/AppListFormatter.swift
- Sources/mas/Formatters/SearchResultFormatter.swift
- Sources/mas/Network/URL.swift
- Tests/masTests/Models/SoftwareProductSpec.swift
Remove unnecessary imports.
Resolve #709
> Remove unnecessary imports

- .swiftlint.yml
- Tests/masTests/.swiftlint.yml
Update SwiftLint config for 0.58.0.
Resolve #711
> Update SwiftLint config for 0.58.0

- .swiftlint.yml
- Package.resolved
- Package.swift
- README.md
- Tests/masTests/.swiftlint.yml
- script/bootstrap
- script/build
- script/lint
- script/release_cancel
> Improvements

- README.md
> Simplify emoji

- Package.resolved
- Package.swift
- Tests/masTests/Commands/AccountSpec.swift
- Tests/masTests/Commands/HomeSpec.swift
- Tests/masTests/Commands/InfoSpec.swift
- Tests/masTests/Commands/InstallSpec.swift
- Tests/masTests/Commands/ListSpec.swift
- Tests/masTests/Commands/LuckySpec.swift
- Tests/masTests/Commands/OpenSpec.swift
- Tests/masTests/Commands/OutdatedSpec.swift
- Tests/masTests/Commands/PurchaseSpec.swift
- Tests/masTests/Commands/SearchSpec.swift
- Tests/masTests/Commands/SignInSpec.swift
- Tests/masTests/Commands/SignOutSpec.swift
- Tests/masTests/Commands/UninstallSpec.swift
- Tests/masTests/Commands/UpgradeSpec.swift
- Tests/masTests/Commands/VendorSpec.swift
- Tests/masTests/Commands/VersionSpec.swift
- Tests/masTests/Controllers/ITunesSearchAppStoreSearcherSpec.swift
- Tests/masTests/Formatters/AppListFormatterSpec.swift
- Tests/masTests/Formatters/SearchResultFormatterSpec.swift
- Tests/masTests/Models/SearchResultListSpec.swift
- Tests/masTests/Models/SearchResultSpec.swift
- Tests/masTests/Models/SoftwareProductSpec.swift
Upgrade Nimble to 13.7.1 & Quick to 7.6.2.
Resolve #732
> Upgrade Nimble to 13.7.1 & Quick to 7.6.2

- Sources/mas/Controllers/SoftwareMapAppLibrary.swift
Case-insensitively sort installed apps by app name.
Resolve #733
> Case-insensitively sort installed apps by app name

- .github/dependabot.yml
Check for Quick & Nimble updates in dependabot.
Resolve #742
> Check for Quick & Nimble updates in dependabot

- Sources/mas/Controllers/SpotlightSoftwareMap.swift
Fix installed app displayed names.
Resolve #746
> Fix installed app displayed names

- Sources/mas/Controllers/AppStoreSearcher.swift
- Sources/mas/Controllers/ITunesSearchAppStoreSearcher.swift
Improve `*AppStoreSearcher` DocC.
Resolve #755
> Improve `*AppStoreSearcher` DocC

- Sources/mas/Controllers/AppLibrary.swift
- Sources/mas/Controllers/SoftwareMapAppLibrary.swift
Improve `*AppLibrary` DocC.
Resolve #757
> Improve `*AppLibrary` DocC

- Sources/mas/AppStore/PurchaseDownloadObserver.swift
- Sources/mas/AppStore/SSPurchase.swift
Fix app installation output.
Resolve #759
> Fix app installation output

- Sources/mas/Commands/Upgrade.swift
- Sources/mas/Controllers/SoftwareMapAppLibrary.swift
When upgrading apps, don't short circuit when encountering any app ID that is unknown to the MAS.
Resolve #765
> When upgrading apps, don't short circuit when encountering any app ID that is unknown to the MAS

- Package.resolved
- Package.swift
- Sources/mas/AppStore/CKSoftwareProduct+SoftwareProduct.swift
- Sources/mas/AppStore/Downloader.swift
- Sources/mas/AppStore/PurchaseDownloadObserver.swift
- Sources/mas/AppStore/SSPurchase.swift
- Sources/mas/Commands/Config.swift
- Sources/mas/Commands/Install.swift
- Sources/mas/Commands/Lucky.swift
- Sources/mas/Commands/Outdated.swift
- Sources/mas/Commands/Purchase.swift
- Sources/mas/Commands/Uninstall.swift
- Sources/mas/Commands/Upgrade.swift
- Sources/mas/Controllers/SpotlightSoftwareMap.swift
- Sources/mas/Formatters/AppListFormatter.swift
- Sources/mas/Formatters/Utilities.swift
- Sources/mas/Models/SoftwareProduct.swift
Improve concurrency & other cleanup.
Resolve #770
> Improve concurrency & other cleanup

- Sources/mas/AppStore/Downloader.swift
- Sources/mas/AppStore/ISStoreAccount.swift
- Sources/mas/AppStore/SSPurchase.swift
- Sources/mas/Commands/Account.swift
- Sources/mas/Commands/SignIn.swift
- Tests/masTests/Commands/AccountSpec.swift
Reenable `account` for macOS 11-.
Resolve #781
> Reenable `account` for macOS 11-

- Sources/mas/Models/SimpleSoftwareProduct.swift
- Sources/mas/Models/SoftwareProduct.swift
- Tests/masTests/Commands/UninstallSpec.swift
Make `SoftwareProduct` & `SimpleSoftwareProduct` immutable.
Resolve #787
> Make `SoftwareProduct` & `SimpleSoftwareProduct` immutable

- README.md
- Sources/mas/Commands/Account.swift
- Sources/mas/Commands/SignIn.swift
- Sources/mas/Commands/SignOut.swift
- Sources/mas/Errors/MASError.swift
- contrib/completion/mas.fish
Reword "Apple ID" as "Apple Account".
Resolve #786
> Reword "Apple ID" as "Apple Account"

- Sources/mas/AppStore/Downloader.swift
- Sources/mas/AppStore/PurchaseDownloadObserver.swift
- Sources/mas/Commands/Install.swift
- Sources/mas/Commands/Lucky.swift
- Sources/mas/Commands/Outdated.swift
- Sources/mas/Commands/Purchase.swift
- Sources/mas/Commands/Reset.swift
- Sources/mas/Commands/Search.swift
- Sources/mas/Commands/Uninstall.swift
- Sources/mas/Commands/Upgrade.swift
- Sources/mas/Controllers/SoftwareMapAppLibrary.swift
- Sources/mas/Formatters/AppInfoFormatter.swift
- docs/sample.swift
Improve output code:
- Print using variadic arguments instead of using interpolated strings.
- Use multiline strings where appropriate.
- Inline single-use variables.
- Merge consecutive prints.
Resolve #796
> Improve output code.

- Sources/mas/AppStore/Downloader.swift
- Sources/mas/Commands/SignIn.swift
- Sources/mas/Controllers/AppLibrary.swift
- Sources/mas/Controllers/SoftwareMapAppLibrary.swift
- Sources/mas/Models/SimpleSoftwareProduct.swift
- Tests/masTests/Commands/OutdatedSpec.swift
- Tests/masTests/Commands/UninstallSpec.swift
Remove unused imports.
Resolve #799
> Remove unused imports

- .github/workflows/build-test.yml
- .github/workflows/tag-pushed.yml
Upgrade Xcode to 16.3 on GHA macos-15 runners.
Resolve #816
> Upgrade Xcode to 16.3 on GHA macos-15 runners

- .github/workflows/release-published.yml
Remove the homebrew-core bump step from `release-published.yml`.
Resolve #819
> Remove the homebrew-core bump step from `release-published.yml`

- Sources/mas/AppStore/ISStoreAccount.swift
Remove `@retroactive`.
Resolve #818
> Remove `@retroactive`

- .markdownlint.json
- .swiftlint.yml
- Sources/mas/Commands/Uninstall.swift
- Sources/mas/Formatters/AppListFormatter.swift
- contrib/completion/mas.fish
- script/format
- script/generate_token
- script/lint
- script/package
- script/test
Improve code spacing.
Resolve #828
> Improve code spacing

- script/package
Change package identifier from `com.mphys.mas-cli` to `io.github.mas-cli`.
Resolve #673
> Change package identifier from `com.mphys.mas-cli` to `io.github.mas-cli`

- Sources/mas/Commands/Home.swift
- Sources/mas/Commands/Open.swift
- Sources/mas/Commands/Vendor.swift
- Sources/mas/Errors/MASError.swift
Improve URL parsing error handling.
Resolve #842
> Improve URL parsing error handling

- Sources/mas/.swiftlint.yml
- Sources/mas/AppStore/PurchaseDownloadObserver.swift
- Sources/mas/Commands/Account.swift
- Sources/mas/Commands/Config.swift
- Sources/mas/Commands/Info.swift
- Sources/mas/Commands/List.swift
- Sources/mas/Commands/Outdated.swift
- Sources/mas/Commands/Region.swift
- Sources/mas/Commands/Search.swift
- Sources/mas/Commands/Uninstall.swift
- Sources/mas/Commands/Upgrade.swift
- Sources/mas/Commands/Version.swift
- Sources/mas/Formatters/Printing.swift
- docs/sample.swift
Improve output code.
Resolve #808
> Improve output code

- .swift-format
- .swiftformat
- .swiftlint.yml
- Sources/mas/.swiftlint.yml
- Sources/mas/AppStore/Downloader.swift
- Sources/mas/AppStore/PurchaseDownloadObserver.swift
- Sources/mas/Commands/Lucky.swift
- Sources/mas/Commands/Outdated.swift
- Sources/mas/Commands/Uninstall.swift
- Sources/mas/Commands/Upgrade.swift
- Sources/mas/Controllers/ITunesSearchAppStoreSearcher.swift
- Sources/mas/Controllers/SpotlightInstalledApps.swift
- Sources/mas/Errors/MASError.swift
- Sources/mas/Formatters/SearchResultFormatter.swift
- Sources/mas/Models/InstalledApp.swift
- Sources/mas/Utilities/Finder.swift
- Tests/masTests/.swift-format
- Tests/masTests/.swiftlint.yml
- Tests/masTests/Controllers/ITunesSearchAppStoreSearcherSpec.swift
> Improve linting

- .markdownlint-cli2.yaml
- .periphery.yaml
- .swiftlint.yml
- Package.swift
- Sources/mas/AppStore/AppleAccount.swift
- Sources/mas/AppStore/ISORegion.swift
- Sources/mas/Commands/SignIn.swift
- Sources/mas/Controllers/SpotlightInstalledApps.swift
- Sources/mas/Formatters/Printing.swift
- Sources/mas/Models/SearchResultList.swift
- Sources/mas/Utilities/Finder.swift
- script/lint
- script/test
Improve build, lint & test.
Resolve #872
> Improve build, lint & test

- Brewfile
- Package.swift
- Sources/mas/Commands/SignIn.swift
- Sources/mas/Models/InstalledApp.swift
- script/build
Build on older versions of Xcode.
Resolve #874
> Build on older versions of Xcode

- CODE_OF_CONDUCT.md
- README.md
- docs/style.md
Update documentation & badges.
Resolve #876
> Update documentation & badges

- .swiftlint.yml
- Sources/mas/AppStore/Downloader.swift
- Sources/mas/Commands/Home.swift
- Sources/mas/Commands/Info.swift
- Sources/mas/Commands/Install.swift
- Sources/mas/Commands/Lucky.swift
- Sources/mas/Commands/OptionGroups/AppIDsOptionGroup.swift
- Sources/mas/Commands/OptionGroups/ForceOptionGroup.swift
- Sources/mas/Commands/OptionGroups/SearchTermOptionGroup.swift
- Sources/mas/Commands/OptionGroups/VerboseOptionGroup.swift
- Sources/mas/Commands/Outdated.swift
- Sources/mas/Commands/Purchase.swift
- Sources/mas/Commands/Search.swift
- Sources/mas/Commands/Uninstall.swift
- Sources/mas/Commands/Upgrade.swift
- Sources/mas/Commands/Vendor.swift
- Sources/mas/Errors/MASError.swift
- contrib/completion/mas.fish
Add & use SAP `@OptionGroup`s for arguments.
Resolve #880
> Add & use SAP `@OptionGroup`s for arguments

- .editorconfig
- .github/dependabot.yaml
- .github/release.yaml
- .markdownlint-cli2.yaml
- .periphery.yaml
- .swiftformat
- .swiftlint.yml
- .yamllint.yaml
- Sources/mas/.swiftlint.yml
- Tests/masTests/.swiftlint.yml
Cleanup lint config & other files.
Resolve #893
> Cleanup lint config & other files

- Sources/mas/AppStore/Downloader.swift
Fix network warning.
Resolve #898
> Fix network warning

- Package.resolved
- Package.swift
- Sources/mas/Formatters/Printer.swift
- Sources/mas/Models/InstalledApp.swift
Use SAP main branch & minor code cleanup.
Resolve #900
> Use SAP main branch & minor code cleanup

- Package.resolved
- Package.swift
Upgrade IsoCountryCodes to 1.0.3.
Resolve #902
> Upgrade IsoCountryCodes to 1.0.3

- .github/workflows/tag-pushed.yaml
- .swiftformat
- .swiftlint.yml
- CODE_OF_CONDUCT.md
- Sources/mas/.swiftlint.yml
- Sources/mas/Commands/SignIn.swift
- Sources/mas/Commands/Uninstall.swift
- Sources/mas/Formatters/Printer.swift
- Sources/mas/Models/InstalledApp.swift
- Sources/mas/Utilities/ProcessInfo.swift
- Tests/masTests/.swiftlint.yml
Miscellaneous cleanup.
Resolve #912
> Miscellaneous cleanup

- .periphery.yaml
- .swiftformat
- Package.resolved
- Package.swift
- Tests/masTests/Models/SearchResultSpec.swift
Update dependencies & linting.
Resolve #919
> Update dependencies & linting

- Scripts/generate_manual
Generate manual via `Scripts/generate_manual`.
Resolve #865
> Generate manual via `Scripts/generate_manual`

- Scripts/package
Add package installer title.
Resolve #924
> Add package installer title

- .swiftlint.yml
- Brewfile
- Sources/mas/.swiftlint.yml
- Tests/masTests/.swiftlint.yml
Update SwiftLint to 0.60.0.
Resolve #931
> Update SwiftLint to 0.60.0

- .github/workflows/build-test.yaml
- .github/workflows/codeql.yaml
- .github/workflows/release-published.yaml
- .github/workflows/tag-pushed.yaml
Run `build-test` GHA workflow on macOS-15, macos-14 & macos-13.
Update some dependencies.
> Run `build-test` GHA workflow on macOS-15, macos-14 & macos-13

- Sources/mas/Commands/List.swift
- Tests/masTests/Commands/ListSpec.swift
Change `list` error to warning.
Resolve #929
> Change `list` error to warning

- Sources/mas/Commands/Reset.swift
Improve `Reset`. Remove `--debug` flag.
Resolve #941
> Improve `Reset`. Remove `--debug` flag.

- .github/workflows/build-test.yaml
- .github/workflows/codeql.yaml
- .github/workflows/release-published.yaml
- .github/workflows/tag-pushed.yaml
Setup macOS 26 GHA runner.
Resolve #940
> Setup macOS 26 GHA runner

- .swiftlint.yml
- Package.resolved
- Package.swift
- Sources/mas/AppStore/ISORegion.swift
- Sources/mas/Commands/Config.swift
- Sources/mas/Commands/Region.swift
- Sources/mas/Controllers/AppStoreSearcher.swift
- Sources/mas/Controllers/ITunesSearchAppStoreSearcher.swift
- Tests/masTests/Controllers/MockAppStoreSearcher.swift
Improve region handling. No longer use IsoCountryCodes library.
Resolve #948
> Improve region handling. No longer use IsoCountryCodes library.

- Sources/mas/Controllers/AppStoreSearcher.swift
> Code cleanup

- .github/workflows/build-test.yaml
- Sources/mas/Formatters/AppListFormatter.swift
- Sources/mas/Formatters/SearchResultFormatter.swift
- Tests/masTests/Commands/SearchTests.swift
- Tests/masTests/Formatters/AppListFormatterTests.swift
- Tests/masTests/Formatters/SearchResultFormatterTests.swift
Improve ADAM ID display padding.
Resolve #952
> Improve ADAM ID display padding

- Tests/masTests/Formatters/SearchResultFormatterTests.swift
> Improve spacing

- Scripts/update_headers
Improve `Scripts/update_headers`.
Resolve #961
> Improve `Scripts/update_headers`

- .swiftformat
- Brewfile
Upgrade swiftformat to 0.58.2.
Resolve #977
> Upgrade swiftformat to 0.58.2

- Package.resolved
- Package.swift
Upgrade swift-collections to 1.3.0.
Resolve #980
> Upgrade swift-collections to 1.3.0

- .gitignore
- .swiftformat
- Brewfile
- Package.swift
- Scripts/clean
Fix Xcode build & other cleanup.
Resolve #990
> Fix Xcode build & other cleanup

- Tests/MASTests/Utilities/Consequences.swift
Fix data race in `Consequences.swift`.
Deduplicate `Consequences.swift`.
Resolve #1001
> Fix data race in `Consequences.swift`.

- Sources/mas/Formatters/Printer.swift
Deduplicate `Printer`.
Use `FileHandle` instead of `UnsafeMutablePointer` in `Printer`.
Resolve #1003
> Improve `Printer`

- Sources/mas/Commands/Outdated.swift
Parallelize `outdated`.
Resolve #1004
> Parallelize `outdated`
